export const enum TypeError {
  NOT_ENOUGH_MONEY = 'NOT_ENOUGH_MONEY',
  NOT_FOUND_RESET_CODE_TOKEN = 'NOT_FOUND_RESET_CODE_TOKEN',
  NOT_FOUND_RESET_PASSWORD_TOKEN = 'NOT_FOUND_RESET_PASSWORD_TOKEN',
  RESET_CODE_IS_NOT_EXPIRES = 'RESET_CODE_IS_NOT_EXPIRES',
  RESET_CODE_INVALID = 'RESET_CODE_INVALID',
  RESET_CODE_TOKEN_INVALID = 'RESET_CODE_TOKEN_INVALID',
  RESET_PASSWORD_TOKEN_INVALID = 'RESET_PASSWORD_TOKEN_INVALID',
}
